### ISSUE TITLE
aarch64-debug-kernel

### ISSUE THREAD

**Issue by idersan** [rf972/lisa-qemu#6]
hi sir, from [aarch64 debug kernel](https://futurewei-cloud.github.io/ARM-Datacenter/qemu/aarch64-debug-kernel/) , the initrd.img-5.5.11 copy form a ubuntu.img, where the 'ubuntu.img' do i get it? and also the 'mini_ubuntu.img' mean it is from lisa-qemu/build/VM-ubuntu.aarch64/ubuntu.aarch64.img, is it?

**Comment by rf972** [comment]
To use lisa-qemu generated images with [this procedure](https://futurewei-cloud.github.io/ARM-Datacenter/qemu/aarch64-debug-kernel/) we can use ubuntu.aarch64.img in the places where the documentation references *ubuntu.img.   Ubuntu.aarch64.img should have an ititrd that can be copied out as per the examples.
